name: Ejecución manual de despliegue de infraestructura

on:
  worlflow_dispatch:
    inputs:
      command:
        choice:
          - plan
          - apply
          - destroy
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configurar credenciales AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Inicializar Terraform
        run: terraform init

      - name: Ejecutar comando seleccionado
        run: terraform ${{ github.event.inputs.command }}
